import { TypographyH1 } from "@/components/ui/typography";
import Head from "next/head";
import { useAuthState } from "react-firebase-hooks/auth";
import { auth } from "~/client/firebase";
import InitialVideoModal from "~/components/InitialVideoModal";
import NavigationBar from "~/components/Navigation";
import Redirect from "~/components/Redirect";
import AddAutomation, { type Sensor } from "~/components/AddAutomation";
import LineChart from "~/components/LineChart";
import { useRefData } from "~/client/hooks/useRefData";

export default function Home() {
  const [user, loading] = useAuthState(auth);
  const [sensors, loadingSensors] = useRefData<Sensor>({ path: "sensors" });

  if (!loading && !user) return <Redirect path="/login" />;

  return (
    <>
      <Head>
        <title>Smart Home Automator</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <nav className="px-4 py-2">
        <NavigationBar />
      </nav>
      <main className="px-4 py-2">
        {user && !loading && (
          <>
            <InitialVideoModal />
            <TypographyH1>Smart Home Automator</TypographyH1>
            <AddAutomation />
          </>
        )}

        {loadingSensors && <p>Loading sensors...</p>}
        {!loadingSensors && sensors && (
          <div className="grid grid-cols-1 gap-4">
            {sensors.map((sensor) => (
              <LineChart key={sensor.id} sensor={sensor} />
            ))}
          </div>
        )}
      </main>
    </>
  );
}
