import { TypographyH1 } from "@/components/ui/typography";
import Head from "next/head";
import { useAuthState } from "react-firebase-hooks/auth";
import { auth } from "~/client/firebase";
import InitialVideoModal from "~/components/InitialVideoModal";
import NavigationBar from "~/components/Navigation";
import Redirect from "~/components/Redirect";
import AddAutomation from "~/components/AddAutomation";
import { useEffect } from "react";
import {
  type Action,
  type Measurement,
  determineActions,
} from "~/client/utils/determineActions";

export default function Home() {
  const [user, loading] = useAuthState(auth);

  useEffect(() => {
    const actions: Array<Action> = [
      {
        actuatorId: "1",
        trigger: "gt",
        sensorId: "1",
        newState: {
          enabled: true,
          metadata: {
            value: 0,
          },
          stopAfter: 0,
        },
      },
    ];

    const measurements: Array<Measurement> = [
      { sensorId: "1", value: 1, timestamp: 123224392 },
      { sensorId: "1", value: 1, timestamp: 123224392 },
      { sensorId: "1", value: 1, timestamp: 123224392 },
    ];

    const ans = determineActions(actions, measurements);
    console.log(ans);
  }, []);

  if (!loading && !user) return <Redirect path="/login" />;

  return (
    <>
      <Head>
        <title>Smart Home Automator</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <nav className="px-4 py-2">
        <NavigationBar />
      </nav>
      <main className="px-4 py-2">
        {user && !loading && (
          <>
            <InitialVideoModal />
            <TypographyH1>Smart Home Automator</TypographyH1>
            <AddAutomation />
          </>
        )}
      </main>
    </>
  );
}
