import { TypographyH1 } from "@/components/ui/typography";
import Head from "next/head";
import { useAuthState } from "react-firebase-hooks/auth";
import { auth } from "~/client/firebase";
import InitialVideoModal from "~/components/InitialVideoModal";
import Redirect from "~/components/Redirect";
import AddAutomation from "~/components/AddAutomation";
import AllAutomations from "~/components/AllAutomations";

export default function Home() {
  const [user, loading] = useAuthState(auth);

  if (!loading && !user) return <Redirect path="/login" />;

  return (
    <>
      <Head>
        <title>Smart Home Automator</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="px-4 py-2">
        {user && !loading && (
          <>
            <InitialVideoModal />
            <TypographyH1>Smart Home Automator</TypographyH1>
            <AddAutomation />
            <AllAutomations />
          </>
        )}
      </main>
    </>
  );
}
