import type { NextPage } from "next";
import Head from "next/head";
import { useAuthState } from "react-firebase-hooks/auth";
import { auth } from "~/client/firebase";
import { useRefData } from "~/client/hooks/useRefData";
import { type Sensor } from "~/components/AddAutomation";
import LineChart from "~/components/LineChart";
import Redirect from "~/components/Redirect";

interface VisualizePageProps {
  children?: React.ReactNode;
}

const VisualizePage: NextPage<VisualizePageProps> = () => {
  const [user, loading] = useAuthState(auth);
  const [sensors, loadingSensors] = useRefData<Sensor>({ path: "sensors" });

  if (!loading && !user) return <Redirect path="/login" />;

  return (
    <div className="p-4 pr-6">
      <Head>
        <title>Visualización - Smart Home Automator</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {loadingSensors && <p>Loading sensors...</p>}
      {!loadingSensors && sensors && (
        <div className="grid grid-cols-1 gap-4">
          {sensors.map((sensor) => (
            <LineChart key={sensor.id} sensor={sensor} />
          ))}
        </div>
      )}
    </div>
  );
};

export default VisualizePage;
